service: aws-sns-basic

# Step 1. In this_file, Define a `custom` block and add `topicName`. We will use this reference in other areas of `serverless.yml` #

provider:
  name: aws
  runtime: nodejs22.x
  # Step 3. In this_file, Expose the `TOPIC_NAME` to `environment` variables using the `${self:custom.topicName}` reference #
  # Step 4. In this_file, Create the IAM role `iamRoleStatements` needed to `sns:Publish`. This allows for our `eventProducer` function to publish messages to our SNS topic.
