
service: event-driven-app

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MY_TABLE: { Ref: myDynamoTable }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        # Step 3. In this_file, the IAM role must be updated to include `dynamodb:DeleteItem` permission
        # Step 7. In this_file, You will need the `GetRecords`, `GetShardIterator`, `DescribeStream`, `ListStreams` permissions for Dynamo Stream access.
      Resource: { Fn::GetAtt: [ myDynamoTable, Arn ] }

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  scan:
    handler: handler.scan
    events:
      - http:
          path: scan
          method: post
          cors: true
  # Add a `delete` function triggered by an http POST
  # Step 1. In this_file, Add a `delete` function triggered by an http POST event #
  # Step 8. Add a `handleStream` function triggered by a dynamo Stream http://bit.ly/2mhkJne in this_file

resources:
  Resources:
    myDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'my-table-name'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        # Step 6. add a stream to the dynamoDB table by setting the `StreamSpecification` property on the `Properties` of the CloudFormation declaration of the table. Set `StreamViewType: NEW_AND_OLD_IMAGES`
